### ISSUE TITLE
The list could be structured as a tree of tasks and subtasks.

### ISSUE THREAD

**Issue by agostinhosamil** [philldev/todo-app-v2#1]
The todo list should be a _tree structure_ of divided tasks into sub-tasks divided the sub-tasks further.

Such as the list bellow:

- First todo
  - First Child of the First todo
  - Second Child of the First todo
- Second Todo
- Third Todo
  - First Child of the Third todo

**Comment by philldev** [comment]
That's a great idea! I'll work on that. Thanks

**Comment by philldev** [comment]
> The todo list should be a _tree structure_ of divided tasks into sub-tasks divided the sub-tasks further.
> 
> Such as the list bellow:
> 
> * First todo
>   
>   * First Child of the First todo
>   * Second Child of the First todo
> * Second Todo
> * Third Todo
>   
>   * First Child of the Third todo

That's a great idea! I'll work on that. Thanks

**Comment by philldev** [comment]
Ive added on the develop branch check it out!
